"""
10 realistic Theben-style products as seed data.
Intentionally with slight inconsistencies (missing fields, varying unit formatting)
to demonstrate normalization needs.
"""

PRODUCTS = [
    # ── Timers ──────────────────────────────────────────────────────────────────
    {
        "article_number": "TR 610 top2",
        "name": "Timer TR 610 top2",
        "family": "Timer",
        "attributes": {
            "voltage": "230 V AC",
            "switching_capacity": "3680 W",
            "switching_cycles_per_day": 48,
            "accuracy": "±1 s/day",
            "protection_class": "IP 20",
            "module_width": "2 MW",
            "certifications": ["CE", "VDE"],
            "rohs_compliant": True,
            "operating_temperature": "-10 … +55 °C",
            "launch_date": "2019-03-01",
        },
    },
    {
        "article_number": "TR 612 top2",
        "name": "Timer TR 612 top2 (16A)",
        "family": "Timer",
        "attributes": {
            "voltage": "230V AC",
            "switching_capacity": "3680W",
            "switching_cycles_per_day": 48,
            "accuracy": "±1 s/day",
            "protection_class": "IP20",
            "module_width": "2 MW",
            "certifications": ["CE", "VDE", "UL"],
            "rohs_compliant": True,
            "operating_temperature": "-10 to +55 °C",
            "launch_date": "2020-06-15",
        },
    },
    {
        "article_number": "TR 624 top2",
        "name": "Annual Timer TR 624 top2",
        "family": "Timer",
        "attributes": {
            "voltage": "230 V AC",
            "switching_capacity": "3680 W",
            "switching_cycles_per_day": 96,
            "accuracy": "±0.5 s/day",
            "protection_class": "IP 20",
            "module_width": "4 MW",
            "certifications": ["CE", "VDE"],
            "rohs_compliant": True,
            "operating_temperature": "-10 … +55 °C",
            "launch_date": "2021-01-10",
        },
    },

    # ── Motion Sensors ──────────────────────────────────────────────────────────
    {
        "article_number": "LUXA 102-360",
        "name": "Motion Sensor LUXA 102-360",
        "family": "Motion Sensor",
        "attributes": {
            "voltage": "230 V AC",
            "detection_angle": 360,
            "range": "12 m",
            "switching_capacity": "1000 W",
            "follow_up_time": "1 s … 30 min",
            "light_threshold": "10 … 2000 Lux",
            "protection_class": "IP 44",
            "mounting": "Ceiling",
            "certifications": ["CE"],
            "rohs_compliant": True,
            "reach_compliant": True,
            "launch_date": "2018-09-01",
        },
    },
    {
        "article_number": "LUXA 104-360",
        "name": "Motion Sensor LUXA 104-360 (Outdoor)",
        "family": "Motion Sensor",
        "attributes": {
            "voltage": "230 V AC",
            "detection_angle": 360,
            "range": "12m",
            "switching_capacity": "2300 W",
            "follow_up_time": "10 s … 30 min",
            "light_threshold": "2 … 2000 Lux",
            "protection_class": "IP 55",
            "mounting": "Ceiling/Wall",
            "certifications": ["CE", "VDE"],
            "rohs_compliant": True,
            "launch_date": "2019-02-14",
        },
    },
    {
        "article_number": "PD 180i KNX",
        "name": "Presence Detector PD 180i KNX",
        "family": "Motion Sensor",
        "attributes": {
            "voltage": "29 V DC (KNX)",
            "detection_angle": 180,
            "range": "8 m",
            "switching_capacity": None,
            "follow_up_time": "10 s … 60 min",
            "light_threshold": "0 … 2000 Lux",
            "protection_class": "IP 20",
            "mounting": "Ceiling",
            "certifications": ["CE", "KNX"],
            "rohs_compliant": True,
            "reach_compliant": True,
            "launch_date": "2022-03-07",
        },
    },
    {
        "article_number": "ARGUS 220 KNX",
        "name": "Presence Detector ARGUS 220 KNX",
        "family": "Motion Sensor",
        "attributes": {
            "voltage": "29V DC (KNX)",
            "detection_angle": 220,
            "range": "10 m",
            "switching_capacity": None,
            "follow_up_time": "10 s … 60 min",
            "light_threshold": "0 … 2000 Lux",
            "protection_class": "IP 20",
            "mounting": "Wall",
            "certifications": ["CE", "KNX", "VDE"],
            "rohs_compliant": True,
            "reach_compliant": True,
            "launch_date": "2023-01-20",
        },
    },

    # ── Room Thermostats ────────────────────────────────────────────────────────
    {
        "article_number": "RAMSES 831 top2",
        "name": "Room Thermostat RAMSES 831 top2",
        "family": "Room Thermostat",
        "attributes": {
            "voltage": "230 V AC",
            "temperature_range": "+5 … +30 °C",
            "switching_differential": "0.3 K",
            "output": "Relay 1A",
            "display": True,
            "knx_capable": False,
            "protection_class": "IP 30",
            "mounting_type": "Surface mount",
            "certifications": ["CE", "VDE"],
            "rohs_compliant": True,
            "energy_efficiency_class": "A",
            "launch_date": "2017-11-01",
        },
    },
    {
        "article_number": "RAMSES 833 top2",
        "name": "Room Thermostat RAMSES 833 top2",
        "family": "Room Thermostat",
        "attributes": {
            "voltage": "230 V AC",
            "temperature_range": "+5 … +30 °C",
            "switching_differential": "0.2 K",
            "output": "Relay 2A",
            "display": True,
            "knx_capable": False,
            "protection_class": "IP 30",
            "mounting_type": "Flush mount",
            "certifications": ["CE", "VDE"],
            "rohs_compliant": True,
            "energy_efficiency_class": "A+",
            "launch_date": "2018-04-03",
        },
    },
    {
        "article_number": "RAMSES 862 top2",
        "name": "Room Thermostat RAMSES 862 top2 KNX",
        "family": "Room Thermostat",
        "attributes": {
            "voltage": "29 V DC (KNX)",
            "temperature_range": "+5 … +35 °C",
            "switching_differential": "0.1 K",
            "output": "KNX Bus",
            "display": True,
            "knx_capable": True,
            "protection_class": "IP 20",
            "mounting_type": "Flush mount",
            "certifications": ["CE", "KNX", "VDE"],
            "rohs_compliant": True,
            "energy_efficiency_class": "A++",
            "launch_date": "2021-09-15",
        },
    },
]
